struct VertexInput
{
	float2 inPosition;
	float3 inColor;
};

struct VertexOutput
{
	float4 sv_position : SV_Position;
	float3 color;
};

[shader("vertex")]
VertexOutput vertMain(VertexInput inVertex)
{
	VertexOutput output;
	output.sv_position = float4(inVertex.inPosition,0.0,1.0);
	output.color = inVertex.inColor;
	
	return output;
}

[shader("fragment")]
float4 fragMain(VertexOutput inVert) : SV_Target
{
	float3 color = inVert.color;
	return float4(color,1.0);
}